-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 16:09:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chatbot
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ikaubaya
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ikaubaya
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ikaubaya` DEFAULT CHARACTER SET utf8mb4 ;
USE `ikaubaya` ;

-- -----------------------------------------------------
-- Table `ikaubaya`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ikaubaya`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ikaubaya`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `role_id` INT NOT NULL,
  `angkatan` YEAR NOT NULL,
  `pekerjaan` VARCHAR(45) NOT NULL,
  `fakultas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC),
  INDEX `fk_users_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_users_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `ikaubaya`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `ikaubaya`.`bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `account` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ikaubaya`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ikaubaya`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `header` VARCHAR(45) NULL,
  `content` LONGTEXT NOT NULL,
  `footnote` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`idarticle`),
  INDEX `fk_article_users1_idx` (`users_id` ASC),
  INDEX `fk_article_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_article_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ikaubaya`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ikaubaya`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ikaubaya`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ikaubaya`.`donation` (
  `bank_id` INT NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `amount` BIGINT NOT NULL,
  `message` VARCHAR(45) NULL,
  PRIMARY KEY (`bank_id`, `users_id`),
  INDEX `fk_bank_has_users_users1_idx` (`users_id` ASC),
  INDEX `fk_bank_has_users_bank_idx` (`bank_id` ASC),
  CONSTRAINT `fk_bank_has_users_bank`
    FOREIGN KEY (`bank_id`)
    REFERENCES `ikaubaya`.`bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bank_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `ikaubaya`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
